//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeActivityTraking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.EmployeeToActivities = new HashSet<EmployeeToActivity>();
        }

        [Display(Name = "Номер активности")]
        public int ActivityID { get; set; }
        [Display(Name = "Мероприятие")]
        public string EventID { get; set; }
        [Display(Name = "Тип активности")]
        public int ActivityTypeID { get; set; }
        [Display(Name = "Дата совершения")]
        [Required(ErrorMessage = "Введите дату совершения активности")]
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        [Display(Name = "Статус")]
        public int ActivityStatusID { get; set; }

        public virtual CodifierActivity CodifierActivity { get; set; }
        public virtual CodifierStatusActivity CodifierStatusActivity { get; set; }
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeToActivity> EmployeeToActivities { get; set; }
    }
}
