//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeActivityTraking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CodifierPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodifierPost()
        {
            this.Posts = new HashSet<Post>();
        }

        [Display(Name = "Код должности")]
        [Range(1, int.MaxValue, ErrorMessage = "Допускаются только положительные значения")]
        public int PostID { get; set; }

        [Display(Name = "Должность")]
        [MinLength(2, ErrorMessage = "Минимальная длина наименования должности - 2 символа")]
        [MaxLength(50, ErrorMessage = "Максимальная длина наименования должности - 50 символов")]
        [Required(ErrorMessage = "Введите название должности")]
        public string PostName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
    }
}
