//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeActivityTraking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CodifierActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodifierActivity()
        {
            this.Activities = new HashSet<Activity>();
        }

        [Display(Name = "Код активности")]
        public int ActivityTypeID { get; set; }
        [Display(Name = "Наименование активности")]
        [MinLength(2, ErrorMessage = "Минимальная длина наименования активности - 2 символа")]
        [MaxLength(50, ErrorMessage = "Максимальная длина наименования активности - 50 символов")]
        [Required(ErrorMessage = "Введите название активности")]
        public string ActivityName { get; set; }
        [Display(Name = "Балл")]
        [Range(1, 10, ErrorMessage = "Допускаются значения от 1 до 10 баллов за активность")]
        public int Score { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
