//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeActivityTraking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CodifierSubtypeEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodifierSubtypeEvent()
        {
            this.Events = new HashSet<Event>();
        }

        [Display(Name = "Код подтипа мероприятия")]
        public int SubtypeID { get; set; }
        [Display(Name = "Код типа мероприятия")]
        public int TypeID { get; set; }
        [Display(Name = "Название подтипа мероприятия")]
        [Required(ErrorMessage = "Введите название подтипа мероприятия")]
        public string SubtypeName { get; set; }

        public virtual CodifierTypeEvent CodifierTypeEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
