//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeActivityTraking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActivityTrackingEntities1 : DbContext
    {
        public ActivityTrackingEntities1()
            : base("name=ActivityTrackingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<CodifierActivity> CodifierActivities { get; set; }
        public virtual DbSet<CodifierDepartment> CodifierDepartments { get; set; }
        public virtual DbSet<CodifierFormatEvent> CodifierFormatEvents { get; set; }
        public virtual DbSet<CodifierGender> CodifierGenders { get; set; }
        public virtual DbSet<CodifierPost> CodifierPosts { get; set; }
        public virtual DbSet<CodifierRequestHelp> CodifierRequestHelps { get; set; }
        public virtual DbSet<CodifierStatusActivity> CodifierStatusActivities { get; set; }
        public virtual DbSet<CodifierStatusEvent> CodifierStatusEvents { get; set; }
        public virtual DbSet<CodifierSubtypeEvent> CodifierSubtypeEvents { get; set; }
        public virtual DbSet<CodifierTypeEvent> CodifierTypeEvents { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeToActivity> EmployeeToActivities { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<RequestHelp> RequestHelps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
