//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeActivityTraking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Post : IValidatableObject
    {
        [Display(Name = "Табельный номер")]
        [Required(ErrorMessage = "Введите табельный номер сотрудника")]
        public int EmployeeNumberID { get; set; }
        [Display(Name = "Номер паспорта")]
        public string PassportID { get; set; }
        [Display(Name = "Код должности")]
        [Required(ErrorMessage = "Выберите должность")]
        public int PostID { get; set; }
        [Display(Name = "Код подразделения")]
        [Required(ErrorMessage = "Выберите подразделение")]
        public int DepartmentID { get; set; }
        [Display(Name = "Дата устройства ")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Введите дату устройства на должность")]
        public System.DateTime DateEmployment { get; set; }
        [Display(Name = "Дата увольнения")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateDismissal { get; set; }
    
        public virtual CodifierDepartment CodifierDepartment { get; set; }
        public virtual CodifierPost CodifierPost { get; set; }
        public virtual Employee Employee { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (DateDismissal < DateEmployment)
            {
                yield return new ValidationResult(
                    errorMessage: "Дата увольнения не может быть раньше даты устройства на должность",
                    memberNames: new[] { "DateDismissal" }
               );
            }
        }
    }
}
